name: Default Node CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: lints
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v2
      - name: Setup Node 14 Environment . . .
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Run The Lints . . .
        run:  npm run test:lint
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v2
      - name: Setup Node 14 Environment . . .
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Run The Tests . . .
        run: npm run test
  codecoverage:
    name: codecoverage
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v2
      - name: Setup Node 14 Environment . . .
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Run The Tests . . .
        run: npm run test:coverage
      - name: Codecove Action . . .
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN}} # not required for public repos
          # fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)


